const express = require('express');
const Database = require('better-sqlite3');
const bodyParser = require('body-parser');
const path = require('path');
const fs = require('fs');

const app = express();
const PORT = process.env.PORT || 10000;
const DB_PATH = process.env.DB_PATH || path.join(process.env.RENDER ? '/var/data' : '.', 'absensi_padel.db');
fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');
app.use(bodyParser.json({ limit: '15mb' }));
app.use(bodyParser.urlencoded({ limit: '15mb', extended: true }));
const PUBLIC_DIR = fs.existsSync(path.join(__dirname, 'public')) ? path.join(__dirname, 'public') : path.join(__dirname, 'Public');
app.use(express.static(PUBLIC_DIR));

const LOKASI_PADEL = {
  del_luna: { nama: 'Padel Del Luna', lat: -6.918133332267737, lng: 107.58425180908361, radius_meter: 50, shifts: [{ id: 'L1', nama: 'Shift 1 (07:00 - 15:00)' }, { id: 'L2', nama: 'Shift 2 (14:00 - 22:00)' }, { id: 'L3', nama: 'Shift 3 (Custom)' }] },
  boss_mengger: { nama: 'Padel Boss Mengger', lat: -6.966117949983328, lng: 107.62140225511331, radius_meter: 50, shifts: [{ id: 'M1', nama: 'Shift 1 (08:00 - 16:00)' }, { id: 'M2', nama: 'Shift 2 (13:00 - 23:00)' }, { id: 'M3', nama: 'Shift 3 (Custom)' }] }
};
function hitungJarak(lat1, lon1, lat2, lon2) { const R = 6371e3; const rad = Math.PI / 180; const dLat = (lat2 - lat1) * rad; const dLon = (lon2 - lon1) * rad; const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * rad) * Math.cos(lat2 * rad) * Math.sin(dLon / 2) ** 2; return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }

db.exec(`CREATE TABLE IF NOT EXISTS karyawan (id_karyawan TEXT PRIMARY KEY, nama TEXT NOT NULL, no_hp TEXT NOT NULL, tgl_join DATE NOT NULL);
CREATE TABLE IF NOT EXISTS rekening_karyawan (id INTEGER PRIMARY KEY AUTOINCREMENT, id_karyawan TEXT UNIQUE NOT NULL, nama_bank TEXT NOT NULL, no_rekening TEXT NOT NULL, nama_pemilik TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS komponen_gaji (id INTEGER PRIMARY KEY AUTOINCREMENT, id_karyawan TEXT UNIQUE NOT NULL, gaji_pokok REAL NOT NULL DEFAULT 0, tunjangan_shift REAL NOT NULL DEFAULT 0, tunjangan_weekend REAL NOT NULL DEFAULT 25000, tunjangan_makan_transport REAL NOT NULL DEFAULT 0, bonus_kehadiran REAL NOT NULL DEFAULT 0, lembur_jam REAL NOT NULL DEFAULT 0, tambahan_lain REAL NOT NULL DEFAULT 0, potongan_lain REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS absensi (id INTEGER PRIMARY KEY AUTOINCREMENT, id_karyawan TEXT NOT NULL, kode_lokasi TEXT, lokasi TEXT, shift TEXT, clock_in DATETIME, foto_in TEXT, clock_out DATETIME, foto_out TEXT, tanggal DATE NOT NULL, waktu TIME);`);
const seed = db.prepare('INSERT OR IGNORE INTO karyawan (id_karyawan, nama, no_hp, tgl_join) VALUES (?, ?, ?, ?)');
seed.run('ADMIN', 'Admin', '081111111111', '2026-01-01'); seed.run('PDL-001', 'Nazwa Verylta', '08813099162', '2026-01-15');

app.get('/', (req, res) => res.sendFile(path.join(PUBLIC_DIR, 'index.html')));
app.get('/api/lokasi', (req, res) => res.json(LOKASI_PADEL));
app.get('/api/health', (req, res) => res.json({ status: 'ok', database_path: DB_PATH, persistent_path_configured: Boolean(process.env.DB_PATH || process.env.RENDER) }));
app.get('/api/karyawan', (req, res) => res.json(db.prepare('SELECT * FROM karyawan ORDER BY id_karyawan').all()));
app.get('/api/gaji-lengkap', (req, res) => res.json(db.prepare(`SELECT k.*, r.nama_bank, r.no_rekening, r.nama_pemilik, g.gaji_pokok, g.tunjangan_shift, g.tunjangan_weekend, g.tunjangan_makan_transport, g.bonus_kehadiran, g.lembur_jam, g.tambahan_lain, g.potongan_lain FROM karyawan k LEFT JOIN rekening_karyawan r ON k.id_karyawan=r.id_karyawan LEFT JOIN komponen_gaji g ON k.id_karyawan=g.id_karyawan ORDER BY k.id_karyawan`).all()));
app.get('/api/riwayat', (req, res) => res.json(db.prepare('SELECT a.*, k.nama FROM absensi a JOIN karyawan k ON a.id_karyawan=k.id_karyawan ORDER BY a.id DESC').all()));
app.post('/api/karyawan', (req, res) => { const { id_karyawan, nama, no_hp, tgl_join } = req.body; if (!id_karyawan || !nama) return res.status(400).json({ error: 'ID dan nama wajib diisi.' }); db.prepare('INSERT OR REPLACE INTO karyawan VALUES (?, ?, ?, ?)').run(id_karyawan, nama, no_hp || '-', tgl_join || new Date().toISOString().split('T')[0]); res.json({ message: 'Karyawan berhasil ditambahkan.' }); });
app.put('/api/karyawan/:id', (req, res) => { db.prepare('UPDATE karyawan SET nama=?, no_hp=? WHERE id_karyawan=?').run(req.body.nama, req.body.no_hp || '-', req.params.id); res.json({ message: 'Data diperbarui.' }); });
app.delete('/api/karyawan/:id', (req, res) => { db.prepare('DELETE FROM karyawan WHERE id_karyawan=?').run(req.params.id); res.json({ message: 'Karyawan dihapus.' }); });
app.post('/api/gaji-rekening', (req, res) => { const r = req.body; const tx = db.transaction(() => { db.prepare('INSERT INTO rekening_karyawan (id_karyawan,nama_bank,no_rekening,nama_pemilik) VALUES (?,?,?,?) ON CONFLICT(id_karyawan) DO UPDATE SET nama_bank=excluded.nama_bank,no_rekening=excluded.no_rekening,nama_pemilik=excluded.nama_pemilik').run(r.id_karyawan, r.nama_bank || '', r.no_rekening || '', r.nama_pemilik || ''); db.prepare('INSERT INTO komponen_gaji (id_karyawan,gaji_pokok,tunjangan_shift,tunjangan_weekend,tunjangan_makan_transport,bonus_kehadiran,lembur_jam,tambahan_lain,potongan_lain) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id_karyawan) DO UPDATE SET gaji_pokok=excluded.gaji_pokok,tunjangan_shift=excluded.tunjangan_shift,tunjangan_weekend=excluded.tunjangan_weekend,tunjangan_makan_transport=excluded.tunjangan_makan_transport,bonus_kehadiran=excluded.bonus_kehadiran,lembur_jam=excluded.lembur_jam,tambahan_lain=excluded.tambahan_lain,potongan_lain=excluded.potongan_lain').run(r.id_karyawan, Number(r.gaji_pokok)||0, Number(r.tunjangan_shift)||0, Number(r.tunjangan_weekend)||25000, Number(r.tunjangan_makan_transport)||0, Number(r.bonus_kehadiran)||0, Number(r.lembur_jam)||0, Number(r.tambahan_lain)||0, Number(r.potongan_lain)||0); }); tx(); res.json({ message: 'Data gaji berhasil disimpan.' }); });
app.post('/api/karyawan/import', (req, res) => { const rows = Array.isArray(req.body.rows) ? req.body.rows : []; if (!rows.length || rows.length > 1000) return res.status(400).json({ error: 'Impor harus berisi 1 sampai 1.000 baris.' }); try { const tx = db.transaction(() => rows.forEach((r, i) => { if (!String(r.id_karyawan || '').trim() || !String(r.nama || '').trim()) throw new Error(`Baris ${i + 2}: id_karyawan dan nama wajib diisi.`); db.prepare('INSERT INTO karyawan (id_karyawan,nama,no_hp,tgl_join) VALUES (?,?,?,?) ON CONFLICT(id_karyawan) DO UPDATE SET nama=excluded.nama,no_hp=excluded.no_hp,tgl_join=excluded.tgl_join').run(String(r.id_karyawan).trim(), String(r.nama).trim(), r.no_hp || '-', r.tgl_join || new Date().toISOString().split('T')[0]); db.prepare('INSERT INTO rekening_karyawan (id_karyawan,nama_bank,no_rekening,nama_pemilik) VALUES (?,?,?,?) ON CONFLICT(id_karyawan) DO UPDATE SET nama_bank=excluded.nama_bank,no_rekening=excluded.no_rekening,nama_pemilik=excluded.nama_pemilik').run(r.id_karyawan, r.nama_bank || '', r.no_rekening || '', r.nama_pemilik || ''); db.prepare('INSERT INTO komponen_gaji (id_karyawan,gaji_pokok,tunjangan_shift,tunjangan_weekend,tunjangan_makan_transport,bonus_kehadiran,lembur_jam,tambahan_lain,potongan_lain) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id_karyawan) DO UPDATE SET gaji_pokok=excluded.gaji_pokok,tunjangan_shift=excluded.tunjangan_shift,tunjangan_weekend=excluded.tunjangan_weekend,tunjangan_makan_transport=excluded.tunjangan_makan_transport,bonus_kehadiran=excluded.bonus_kehadiran,lembur_jam=excluded.lembur_jam,tambahan_lain=excluded.tambahan_lain,potongan_lain=excluded.potongan_lain').run(r.id_karyawan, Number(r.gaji_pokok)||0, Number(r.tunjangan_shift)||0, r.tunjangan_weekend === '' ? 25000 : Number(r.tunjangan_weekend)||0, Number(r.tunjangan_makan_transport)||0, Number(r.bonus_kehadiran)||0, Number(r.lembur_jam)||0, Number(r.tambahan_lain)||0, Number(r.potongan_lain)||0); })); tx(); res.json({ message: `${rows.length} data berhasil diperbarui.` }); } catch (err) { res.status(400).json({ error: err.message }); } });
app.post('/api/clock-in', (req, res) => { const r = req.body; const today = new Date().toISOString().split('T')[0]; const lokasi = LOKASI_PADEL[r.kode_lokasi || 'del_luna']; if (r.user_lat !== undefined && hitungJarak(lokasi.lat, lokasi.lng, r.user_lat, r.user_lng) > lokasi.radius_meter) return res.status(403).json({ error: 'Di luar radius lokasi.' }); db.prepare('INSERT INTO absensi (id_karyawan,kode_lokasi,lokasi,shift,clock_in,foto_in,tanggal,waktu) VALUES (?,?,?,?,CURRENT_TIMESTAMP,?,?,?)').run(r.id_karyawan, r.kode_lokasi, lokasi.nama, r.shift || 'Shift 1', r.foto || '', today, new Date().toLocaleTimeString('id-ID')); res.json({ message: 'Check-In Berhasil!' }); });
app.post('/api/clock-out', (req, res) => { const today = new Date().toISOString().split('T')[0]; const row = db.prepare('SELECT id FROM absensi WHERE id_karyawan=? AND tanggal=? AND clock_out IS NULL').get(req.body.id_karyawan, today); if (!row) return res.status(400).json({ error: 'Tidak ada sesi aktif.' }); db.prepare('UPDATE absensi SET clock_out=CURRENT_TIMESTAMP, foto_out=? WHERE id=?').run(req.body.foto || '', row.id); res.json({ message: 'Clock Out Berhasil!' }); });
app.use((req, res) => res.sendFile(path.join(PUBLIC_DIR, 'index.html')));
app.listen(PORT, '0.0.0.0', () => console.log(`Server berjalan pada port ${PORT}`));
